Repository google/digitalbuildings, pull requests merged in 2023-09, with the labels that each got.

#989 Addition of only heating DOAS.
  ontology/yaml/resources/HVAC/entity_types/DOAS.yaml
Labels: info requested from creator, P2

#1128 Addition of a new SDACT with up and down command
  ontology/yaml/resources/HVAC/entity_types/ABSTRACT.yaml
  ontology/yaml/resources/HVAC/entity_types/SDC.yaml
  ontology/yaml/resources/fields/telemetry_fields.yaml
  ontology/yaml/resources/subfields/subfields.yaml
Labels: ready to merge

#1109 Ontology doc cleanup
  ontology/README.md
  ontology/docs/ontology.md
Labels: documentation, P2

#1108 General doc cleanup
  CONTRIBUTING.md
  README.md
  ontology/docs/building_config.md
Labels: documentation, P2
