Repository google/digitalbuildings, pull requests merged in 2023-06, with the labels that each got.

#988 extend OA abstract type
  ontology/yaml/resources/HVAC/entity_types/ABSTRACT.yaml
Labels: P2

#1047 added abstract and canonical types
  ontology/yaml/resources/SAFETY/entity_types/LDS.yaml
Labels: ready to merge

#1045 New weather station & telemtry field
  ontology/yaml/resources/HVAC/entity_types/ABSTRACT.yaml
  ontology/yaml/resources/HVAC/entity_types/WEATHER.yaml
  ontology/yaml/resources/fields/telemetry_fields.yaml
Labels: ready to merge

#1027 added BLR type
  ontology/yaml/resources/HVAC/entity_types/ABSTRACT.yaml
  ontology/yaml/resources/HVAC/entity_types/BLR.yaml
Labels: ready to merge

#1044 ups canonical and abstract types
  ontology/yaml/resources/ELECTRICAL/entity_types/ABSTRACT.yaml
  ontology/yaml/resources/ELECTRICAL/entity_types/GENERALTYPES.yaml
  ontology/yaml/resources/ELECTRICAL/entity_types/UPS.yaml
Labels: ready to merge

#987 new Sensor canonical type and SAQM abstract type
  ontology/yaml/resources/HVAC/entity_types/SENSOR.yaml
Labels: P2, ready to merge
